"""
Django settings for Voyage project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from mongoengine import connect
from django.conf.global_settings import AUTHENTICATION_BACKENDS, SESSION_ENGINE

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$3860kbq*o4y#u@za5v7%ux@5wv^pj8&+%u@n=q3l!wg%*u5a#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    # Aplicações de Terceiros
    'rest_framework',
    'rest_framework.authtoken',
    # Aplicações Internas
    'BaseHistorica',
    'regional'
    
]

MIDDLEWARE_CLASSES = [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Voyage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Voyage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# MongoDB

DATABASE = "oeor"
connect("{database}".format(database=DATABASE))

# Postgresql

DATABASE_ROUTERS = ['BaseHistorica.router.consultaBDHRouter']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    },
    'baseconsolidada': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bccorap_sage',
        'PORT': 5432,
        'USER': 'postgres',
        'PASSWORD': '1qazxsw2!@',
        'HOST': '192.168.28.41', # Seridor BDH
    },
    'basehistorica': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bhcorap_sage',
        'PORT': 5432,
        'USER': 'postgres',
        'PASSWORD': '1qazxsw2!@',
        'HOST': '192.168.28.41', # Seridor BDH
    },             
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

DEFAULT_CHARSET = "utf-8"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}